#!/usr/bin/env node
// Onboards images + descriptions for venues that lack them, by scraping
// og:image / og:description / meta description from each venue's website.
//
// Read-only against Supabase; writes two local files:
//   scripts/venue-image-backfill.sql   — UPDATEs to apply via the dashboard
//   scripts/venue-onboard-report.csv   — every venue tried, with hit/miss reason
//
// Usage:
//   node scripts/venue-onboard.js [--limit N] [--city "Boston"] [--dry-run]
//                                 [--only images|descriptions]
//
// Venues are processed in descending order of upcoming-event count, so the
// head of the run is most of the user-visible value. ~1 request/second.

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const { createClient } = require('@supabase/supabase-js');
const {
  fetchHtml,
  extractMeta,
  validateImageUrl,
  cleanDescription,
  isAggregatorUrl,
  isBoilerplate,
  sqlQuote,
  sleep,
  csvField,
} = require('./lib/og-scrape');

const args = process.argv.slice(2);
const getFlag = (name) => {
  const i = args.indexOf(name);
  return i >= 0 ? args[i + 1] : null;
};
const LIMIT = getFlag('--limit') ? Number(getFlag('--limit')) : Infinity;
const CITY = getFlag('--city');
const DRY_RUN = args.includes('--dry-run');
const ONLY = getFlag('--only'); // 'images' | 'descriptions' | null (both)

const supabase = createClient(
  process.env.EXPO_PUBLIC_SUPABASE_URL,
  process.env.EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY
);

const SQL_PATH = path.join(__dirname, 'venue-image-backfill.sql');
const CSV_PATH = path.join(__dirname, 'venue-onboard-report.csv');

async function fetchAllFutureVenueIds() {
  const today = new Date().toISOString().split('T')[0];
  const counts = new Map();
  for (let page = 0; ; page++) {
    const { data, error } = await supabase
      .from('events_gold')
      .select('venue_id')
      .gte('event_date', today)
      .or('is_deleted.is.null,is_deleted.eq.false')
      .range(page * 1000, page * 1000 + 999);
    if (error) throw error;
    for (const row of data) {
      if (row.venue_id) counts.set(row.venue_id, (counts.get(row.venue_id) || 0) + 1);
    }
    if (data.length < 1000) break;
  }
  return counts;
}

async function main() {
  console.log(`venue-onboard: ${DRY_RUN ? 'DRY RUN' : 'live'}, only=${ONLY || 'both'}, city=${CITY || 'all'}, limit=${LIMIT}`);

  const venues = [];
  for (let page = 0; ; page++) {
    let query = supabase
      .from('venues')
      .select('id, name, city, url, start_url, image, description')
      .eq('is_active', true)
      .or('image.is.null,image.eq.,description.is.null,description.eq.')
      .range(page * 1000, page * 1000 + 999);
    if (CITY) query = query.eq('city', CITY);
    const { data, error } = await query;
    if (error) throw error;
    venues.push(...data);
    if (data.length < 1000) break;
  }

  const eventCounts = await fetchAllFutureVenueIds();
  const needsWork = (v) => {
    const noImage = !v.image;
    const noDesc = !v.description;
    if (ONLY === 'images') return noImage;
    if (ONLY === 'descriptions') return noDesc;
    return noImage || noDesc;
  };

  const targets = venues
    .filter(needsWork)
    .sort((a, b) => (eventCounts.get(b.id) || 0) - (eventCounts.get(a.id) || 0))
    .slice(0, LIMIT);

  console.log(`${venues.length} venues missing something; processing ${targets.length}`);

  const sqlLines = [
    '-- Generated by scripts/venue-onboard.js — og: metadata scraped from venue websites.',
    `-- Generated for ${targets.length} venues. Review before applying (Supabase dashboard).`,
    '-- Guards keep any manually-set value: only empty columns are filled.',
    '',
  ];
  const csvLines = ['venue_id,name,city,url,status,image_found,description_found,reason'];
  let hits = 0;

  for (let i = 0; i < targets.length; i++) {
    const v = targets[i];
    const site = v.url || v.start_url;
    const report = (status, imageFound, descFound, reason) =>
      csvLines.push(
        [v.id, v.name, v.city, site, status, imageFound, descFound, reason].map(csvField).join(',')
      );

    if (!site) {
      report('miss', false, false, 'no website url');
      continue;
    }

    const page = await fetchHtml(site);
    await sleep(1000);
    if (!page) {
      report('miss', false, false, 'fetch failed');
      continue;
    }

    const meta = extractMeta(page.html, page.finalUrl);
    const aggregator = isAggregatorUrl(page.finalUrl);
    const wantImage = !v.image && ONLY !== 'descriptions';
    // Aggregator pages (Ticketmaster & co.) only yield "Buy X tickets..."
    // boilerplate — take their venue photo if any, never their copy.
    const wantDesc = !v.description && ONLY !== 'images' && !aggregator;

    let image = null;
    if (wantImage && meta.ogImage) {
      image = (await validateImageUrl(meta.ogImage)) ? meta.ogImage : null;
    }
    let description = wantDesc
      ? cleanDescription(meta.ogDescription || meta.metaDescription, 500)
      : null;
    if (description && isBoilerplate(description)) description = null;

    if (!image && !description) {
      const reason = aggregator
        ? 'aggregator page, no usable image'
        : wantImage && meta.ogImage
          ? 'og:image failed validation'
          : 'no usable og/meta tags';
      report('miss', false, false, reason);
      continue;
    }

    hits++;
    sqlLines.push(`-- ${v.name} (${v.city}) — ${eventCounts.get(v.id) || 0} upcoming events`);
    if (image) {
      sqlLines.push(
        `UPDATE venues SET image = ${sqlQuote(image)} WHERE id = '${v.id}' AND (image IS NULL OR image = '');`
      );
    }
    if (description) {
      sqlLines.push(
        `UPDATE venues SET description = ${sqlQuote(description)} WHERE id = '${v.id}' AND (description IS NULL OR description = '');`
      );
    }
    sqlLines.push('');
    report('hit', Boolean(image), Boolean(description), aggregator ? 'aggregator: image only' : '');

    if ((i + 1) % 25 === 0) console.log(`  ${i + 1}/${targets.length} done, ${hits} hits`);
  }

  console.log(`Done: ${hits}/${targets.length} venues got new data`);
  if (DRY_RUN) {
    console.log('Dry run — no files written.');
    return;
  }
  fs.writeFileSync(SQL_PATH, sqlLines.join('\n'));
  fs.writeFileSync(CSV_PATH, csvLines.join('\n'));
  console.log(`Wrote ${SQL_PATH}`);
  console.log(`Wrote ${CSV_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
